services:
  postgres:
    image: postgres:latest
    container_name: gastrohubsolo-postgres
    environment:
      POSTGRES_DB: gastrohubsolo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: dbeaver
    ports:
      - "8978:8978"
    depends_on:
      - postgres

volumes:
    postgres_data: